joint_gains: &joint_gains
  p: 300.0
  i: 300.0
  d: 6.0
  i_clamp: 2.0
  i_clamp_max: 2.0
  i_clamp_min: -2.0

joint_goal_threshold: &joint_goal_threshold
  goal: 0.02


whole_body_controller/body:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &joint_name_list
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

  gains:
    shoulder_pan_joint:     *joint_gains
    shoulder_lift_joint:    *joint_gains
    elbow_joint:            *joint_gains
    wrist_1_joint:          *joint_gains
    wrist_2_joint:          *joint_gains
    wrist_3_joint:          *joint_gains

  joint_trajectory_action_node:
    joints: *joint_name_list

    constraints:
      goal_time: 0.6
      shoulder_pan_joint:     *joint_goal_threshold
      shoulder_lift_joint:    *joint_goal_threshold
      elbow_joint:            *joint_goal_threshold
      wrist_1_joint:          *joint_goal_threshold
      wrist_2_joint:          *joint_goal_threshold
      wrist_3_joint:          *joint_goal_threshold
